# Generated by Django 4.2.7 on 2023-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
