# Generated by Django 4.2.7 on 2023-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_producto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.AddField(
            model_name='producto',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
