# Generated by Django 4.2.7 on 2023-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_producto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
