# Generated by Django 4.2.7 on 2023-11-29 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0008_delete_apartados'),
        ('dashboard', '0018_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveBigIntegerField()),
                ('pickup_date', models.DateTimeField(blank=True)),
                ('payment', models.CharField(choices=[('yes', 'Si'), ('no', 'No')], max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.producto')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
