# Generated by Django 4.2.7 on 2023-11-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_precios_alter_apartados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precios',
            options={'verbose_name_plural': 'Precios'},
        ),
    ]
