# Generated by Django 4.2.7 on 2023-11-29 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_precios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
