# Generated by Django 4.2.7 on 2023-11-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_precios_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='category',
        ),
        migrations.RemoveField(
            model_name='precios',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='precios',
            name='type',
        ),
        migrations.AddField(
            model_name='precios',
            name='precio_mirage',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
