# Generated by Django 4.2.7 on 2023-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_producto_category_alter_producto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
