# Generated by Django 4.2.7 on 2023-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
