# Generated by Django 4.2.7 on 2023-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_producto_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='type',
            field=models.CharField(blank=True, choices=[('SETCWC361B', 'SETCWC361B'), ('SETCWC261E', 'SETCWC261E'), ('SETCWC181E', 'SETCWC181E'), ('SETCWC121E', 'SETCWC121E'), ('SETCWC120E', 'SETCWC120E'), ('SETCMC261V', 'SETCMC261V'), ('SETCMC181V', 'SETCMC181V'), ('SETCMC121V', 'SETCMC121V'), ('SETCMC120V', 'SETCMC120V'), ('SETCLC261T', 'SETCLC261T'), ('SETCLC181T', 'SETCLC181T'), ('SETCLC121T', 'SETCLC121T'), ('SETCLC120T', 'SETCLC120T'), ('MBF16AF', 'MBF16AF'), ('MBF10BB', 'MBF10BB'), ('MBF06ZB', 'MBF06ZB'), ('MDD10CB', 'MDD10CB'), ('MDD10CS', 'MDD10CS')], default=None, max_length=100),
        ),
    ]
