# Generated by Django 4.2.7 on 2023-12-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PÚBLICO EN GENERAL', 'PÚBLICO EN GENERAL'), ('TÉCNICO', 'TÉCNICO'), ('PREFERENTE', 'DISTRIBUIDOR PREFERENTE'), ('PLUS', 'DISTRIBUIDOR PLUS'), ('VIP', 'DISTRIBUIDOR VIP')], max_length=50)),
                ('RFC', models.CharField(max_length=100, unique=True)),
                ('DIR', models.CharField(max_length=100)),
                ('CFDI', models.CharField(max_length=100)),
                ('REG_FIS', models.CharField(max_length=100)),
                ('c_email', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=100)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='Profile_Images')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ImageField(blank=True, upload_to='Profile_Images')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
            ],
        ),
    ]
