# Generated by Django 4.2.7 on 2023-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PÚBLICO EN GENERAL', 'PÚBLICO EN GENERAL'), ('PREFERENTE', 'DISTRIBUIDOR PREFERENTE'), ('PLUS', 'DISTRIBUIDOR PLUS'), ('VIP', 'DISTRIBUIDOR VIP')], max_length=50)),
                ('RFC', models.CharField(max_length=100)),
                ('DIR', models.CharField(max_length=100)),
                ('CFDI', models.CharField(max_length=100)),
                ('REG_FIS', models.CharField(max_length=100)),
                ('c_email', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
