# Generated by Django 4.2.7 on 2023-11-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Customer_Images'),
        ),
    ]
