# Generated by Django 4.2.7 on 2023-12-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(choices=[('LIFE 12 - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('LIFE 12 - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('LIFE 12 - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('LIFE 12 - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('LIFE 12 - PLUS 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('LIFE 12 - PLUS 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('LIFE 12 - PLUS 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('LIFE 12 - PLUS 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('XLIFE - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('XLIFE - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('XLIFE - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('XLIFE - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('NEX - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('NEX - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('NEX - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('NEX - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('X32 INVERTER - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('X32 INVERTER - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('X32 INVERTER - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('X32 INVERTER - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('V32 INVERTER - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('V32 INVERTER - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('V32 INVERTER - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('V32 INVERTER - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('MAGNUM 18 INV - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('MAGNUM 22 INV - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('MAGNUM 22 INV - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('MAGNUM 22 INV - 1.5 ton 110V', 'LIFE 12 PLUS 1.5 ton 110'), ('MAGNUM 22 INV - 2 ton 110V', 'LIFE 12 PLUS 2 ton 110'), ('MAGNUM 21 PLATINUM - 1 ton 110V', 'LIFE 12 PLUS 1 ton 110'), ('MAGNUM 21 PLATINUM - 1 ton 220V', 'LIFE 12 PLUS 1 ton 220'), ('X-ONE - 1 ton 110V', 'X-ONE - 1 ton 110V')], max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1, max_length=1000)),
                ('precio_u', models.PositiveIntegerField(max_length=100000)),
                ('descuento', models.DecimalField(decimal_places=5, max_digits=10000)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
