# Generated by Django 4.2.7 on 2023-12-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_pos_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_equipo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pos_equipo',
            name='precio_u',
            field=models.PositiveIntegerField(),
        ),
    ]
