# Generated by Django 4.2.7 on 2023-11-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images'),
        ),
    ]
