# Generated by Django 4.2.7 on 2023-12-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_ficha_precios_alter_pos_equipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_precios',
            name='pos_equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.pos_equipo'),
            preserve_default=False,
        ),
    ]
