# Generated by Django 4.2.7 on 2023-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_ficha_precios_precio_mirage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_precios',
            name='precio_mirage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000),
        ),
    ]
