# Generated by Django 4.2.7 on 2023-12-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_pos_equipo_descuento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ficha_Precios',
        ),
    ]
