# Generated by Django 4.2.7 on 2023-12-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_delete_ficha_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_equipos', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('Transferencia Electrónica', 'Transferencia Electrónica'), ('Efectivo', 'Efectivo'), ('Cheque Nominativo', 'Cheque Nominatico')], max_length=100)),
                ('metodo_pago', models.CharField(choices=[('PUE', 'Pago en una sola exibición'), ('PPD', 'Pago en parcialidades o diferido')], max_length=100)),
                ('tipo_factura', models.CharField(choices=[('Cliente', 'Cliente'), ('Empresa', 'Emprsa'), ('Público en General', 'Publico en General')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.pos_equipo')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
