# Generated by Django 4.2.7 on 2023-12-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_punto_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto_venta',
            name='cantidad_equipos',
        ),
        migrations.RemoveField(
            model_name='punto_venta',
            name='equipo',
        ),
    ]
