# Generated by Django 4.2.7 on 2023-12-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_remove_punto_venta_cantidad_equipos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Punto_Venta',
            new_name='Datos_Venta',
        ),
    ]
