# Generated by Django 4.2.7 on 2023-12-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_rename_punto_venta_datos_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos_venta',
            options={'verbose_name_plural': 'Ordenes de Ventas'},
        ),
        migrations.RenameField(
            model_name='datos_venta',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='datos_venta',
            name='id',
        ),
        migrations.AddField(
            model_name='datos_venta',
            name='folio',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Equipos_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_equipos', models.PositiveBigIntegerField()),
                ('datos_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.datos_venta')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.pos_equipo')),
            ],
            options={
                'verbose_name_plural': 'Total Equipos Vendidos',
            },
        ),
    ]
