# Generated by Django 4.2.7 on 2023-12-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_rename_folio_datos_venta_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos_venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='equipos_venta',
            options={'verbose_name_plural': 'Equipos solicitados'},
        ),
        migrations.RenameField(
            model_name='datos_venta',
            old_name='customer',
            new_name='cliente',
        ),
    ]
