# Generated by Django 4.2.7 on 2023-12-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_alter_datos_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_venta',
            name='forma_pago',
            field=models.CharField(choices=[('Transferencia Electrónica', 'Transferencia Electrónica'), ('Efectivo', 'Efectivo'), ('Cheque Nominativo', 'Cheque Nominativo'), ('Por definir', 'Por definir'), ('Equipo', 'Equipo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Crédito', 'Crédito'), ('Préstamo', 'Préstamo')], max_length=100),
        ),
    ]
